In [3]:
import pandas as pd
df = pd.read_csv('sample_data4.csv')
print(df)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [5]:
df.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

In [6]:
df.sample(5)

    Duration          Date  Pulse  Maxpulse  Calories
3         45  '2020/12/04'    109       175     282.4
11        60  '2020/12/12'    100       120     250.7
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
8         30  '2020/12/09'    109       133     195.1

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     str
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), str(1)
memory usage: 1.4 KB

In [14]:
print(df[["Duration","Pulse"]])

    Duration  Pulse
0         60    110
1         60    117
2         60    103
3         45    109
4         45    117
5         60    102
6         60    110
7        450    104
8         30    109
9         60     98
10        60    103
11        60    100
12        60    100
13        60    106
14        60    104
15        60     98
16        60     98
17        60    100
18        45     90
19        60    103
20        45     97
21        60    108
22        45    100
23        60    130
24        45    105
25        60    102
26        60    100
27        60     92
28        60    103
29        60    100
30        60    102
31        60     92

In [15]:
print(df.loc[0])

Duration              60
Date        '2020/12/01'
Pulse                110
Maxpulse             130
Calories           409.1
Name: 0, dtype: object

In [16]:
print(df.loc[0:2])

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0

In [17]:
print(df.iloc[0])

Duration              60
Date        '2020/12/01'
Pulse                110
Maxpulse             130
Calories           409.1
Name: 0, dtype: object

In [18]:
print(df.iloc[0:2])

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0

In [19]:
print(df[df["Duration"]<60])

    Duration          Date  Pulse  Maxpulse  Calories
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
8         30  '2020/12/09'    109       133     195.1
18        45  '2020/12/18'     90       112       NaN
20        45  '2020/12/20'     97       125     243.0
22        45           NaN    100       119     282.0
24        45  '2020/12/24'    105       132     246.0

In [29]:
print(df[(df["Duration"]< 60) & (df["Pulse"] < 100)])

    Duration          Date  Pulse  Maxpulse  Calories
18        45  '2020/12/18'     90       112       NaN
20        45  '2020/12/20'     97       125     243.0

In [32]:
print(df.sort_values("Date", ascending=False))

    Duration          Date  Pulse  Maxpulse  Calories
26        60      20201226    100       120     250.0
31        60  '2020/12/31'     92       115     243.0
30        60  '2020/12/30'    102       129     380.3
29        60  '2020/12/29'    100       132     280.0
28        60  '2020/12/28'    103       132       NaN
27        60  '2020/12/27'     92       118     241.0
25        60  '2020/12/25'    102       126     334.5
24        45  '2020/12/24'    105       132     246.0
23        60  '2020/12/23'    130       101     300.0
21        60  '2020/12/21'    108       131     364.2
20        45  '2020/12/20'     97       125     243.0
19        60  '2020/12/19'    103       123     323.0
18        45  '2020/12/18'     90       112       NaN
17        60  '2020/12/17'    100       120     300.0
16        60  '2020/12/16'     98       120     215.2
15        60  '2020/12/15'     98       123     275.0
14        60  '2020/12/14'    104       132     379.3
13        60  '2020/12/13'    106       128     345.3
12        60  '2020/12/12'    100       120     250.7
11        60  '2020/12/12'    100       120     250.7
10        60  '2020/12/11'    103       147     329.3
9         60  '2020/12/10'     98       124     269.0
8         30  '2020/12/09'    109       133     195.1
7        450  '2020/12/08'    104       134     253.3
6         60  '2020/12/07'    110       136     374.0
5         60  '2020/12/06'    102       127     300.0
4         45  '2020/12/05'    117       148     406.0
3         45  '2020/12/04'    109       175     282.4
2         60  '2020/12/03'    103       135     340.0
1         60  '2020/12/02'    117       145     479.0
0         60  '2020/12/01'    110       130     409.1
22        45           NaN    100       119     282.0

In [36]:
df.isnull()

    Duration   Date  Pulse  Maxpulse  Calories
0      False  False  False     False     False
1      False  False  False     False     False
2      False  False  False     False     False
3      False  False  False     False     False
4      False  False  False     False     False
5      False  False  False     False     False
6      False  False  False     False     False
7      False  False  False     False     False
8      False  False  False     False     False
9      False  False  False     False     False
10     False  False  False     False     False
11     False  False  False     False     False
12     False  False  False     False     False
13     False  False  False     False     False
14     False  False  False     False     False
15     False  False  False     False     False
16     False  False  False     False     False
17     False  False  False     False     False
18     False  False  False     False      True
19     False  False  False     False     False
20     False  False  False     False     False
21     False  False  False     False     False
22     False   True  False     False     False
23     False  False  False     False     False
24     False  False  False     False     False
25     False  False  False     False     False
26     False  False  False     False     False
27     False  False  False     False     False
28     False  False  False     False      True
29     False  False  False     False     False
30     False  False  False     False     False
31     False  False  False     False     False

In [37]:
print(df.isnull().sum())

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

In [38]:
print(df.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
dtype: bool

In [39]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [40]:
cal_mean = df['Calories'].mean()

In [41]:
print(cal_mean)

304.68